version: '3.8'

services:
  client:
    build: ./client
    ports:
      - "5173:80"
    depends_on:
      - server
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge